<% from "build.inc.yml" import workflow -%>
name: Build Test and Publish Nightly Packages

on:
  schedule:
    # Deliberately scheduled 4 hours after edgedb nightly
    - cron: "0 5 * * *"
  workflow_dispatch:
    inputs: {}
  push:
    branches:
      - nightly

jobs:
  <<- workflow(targets, publications, servers, subdist="nightly") ->>
